spring.datasource.url=jdbc:postgresql://localhost:5434/workflow_db
spring.datasource.username=baza_admin
spring.datasource.password=baza123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

workflow.api.key=BazaMasterKey2026