# 🐘 Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# 🛠️ Configurações do Hibernate (O nosso ORM)
# 'update' cria ou atualiza as tabelas automaticamente (como o prisma db push)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 🚀 Porta da nossa API
server.port=8080